(define (domain farmersriddledomain)
  (:requirements :strips)
  (:predicates (item ?i) (dock ?d) (on ?i ?d) (eats ?i1 ?i2) (onboat ?d))
  (:action moveempty :parameters (?from ?to)
   :precondition (and (not(= ?from ?to)) (onboat ?from) (not (exists (?p1 ?p2) (and (on ?p1 ?from) (on ?p2 ?from) (eats ?p1 ?p2)))))
   :effect (and (onboat ?to) (not (onboat ?from)))
  )
  (:action moveitem :parameters (?from ?to ?item)
   :precondition (and (not(= ?from ?to)) (onboat ?from) (on ?item ?from) 
                      (not (exists (?p1 ?p2) (and (on ?p1 ?from) (on ?p2 ?from) (eats ?p1 ?p2) (not (= ?p1 ?item)) (not (= ?p2 ?item))))))
   :effect (and (onboat ?to) (on ?item ?to) (not (onboat ?from)) (not (on ?item ?from)))
  )
)